# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    build:
      context: .
    develop:
      watch:
      - action: sync
        path: ./src
        target: /app/src
        ignore:
          - node_modules/
      - action: rebuild
        path: package.json
    environment:
      NODE_ENV: production
    ports:
      - 5678:5678